### ISSUE TITLE
Add possibility to fall back to PHP 5.6

### ISSUE THREAD

**Issue by creatoro** [scotch-io/scotch-box-pro#7]
Some older websites are not compatible with PHP 7. I would appreciate the possibility of having PHP 5.6 for those.

**Comment by whatnickcodes** [comment]
You can use older boxes still https://github.com/scotch-io/scotch-box/issues/202

**Comment by creatoro** [comment]
Not really a solution, since I'd use the additions of the new version, especially since I purchased to Pro version.

**Comment by whatnickcodes** [comment]
Right now, there's no plan to allow you to specify which version. The Pro version did come with the Build Scripts if you want to customize a box specific for you.

Otherwise, you can just manually downgrade after provisioning yourself.

https://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04
